[package]
name = "awsx"
version = "0.1.0"
edition = "2018"

authors = [
    "Pit Kleyersburg <pit.kleyersburg@takkt.com>",
    "TAKKT Industrial & Packaging GmbH <webshop-devops@kaiserkraft-europa.de>",
]
license = "Apache-2.0"

autobins = false
publish = false

[[bin]]
name = "awsx"
path = "src/bin/main.rs"

[dependencies]
async-trait = "0.1.41"
atty = "0.2.14"
chrono = "0.4.19"
failure = "0.1.8"
futures = "0.3.7"
git2 = { version = "0.13.12", default-features = false }
indexmap = "1.6"
itertools = "0.9.0"
md-5 = "0.9"
prettytable-rs = "0.8.0"
regex = "1.3.9"
rusoto_autoscaling = "0.45.0"
rusoto_cloudformation = "0.45.0"
rusoto_cloudfront = "0.45.0"
rusoto_core = "0.45.0"
rusoto_credential = "0.45.0"
rusoto_ec2 = "0.45.0"
rusoto_elbv2 = "0.45.0"
rusoto_rds = "0.45.0"
rusoto_s3 = "0.45.0"
rusoto_sts = "0.45.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
tokio = "0.2.22"
uuid = { version = "0.8", features = ["v4"] }
