[package]
name = "awsx"
version = "0.1.0"
edition = "2018"

authors = [
    "Pit Kleyersburg <pit.kleyersburg@takkt.com>",
    "TAKKT Industrial & Packaging GmbH <webshop-devops@kaiserkraft-europa.de>",
]
license = "Apache-2.0"

autobins = false
publish = false

[[bin]]
name = "awsx"
path = "src/bin/main.rs"

[dependencies]
atty = "0.2.13"
chrono = "0.4.10"
failure = "0.1.6"
futures = "0.1.29"
indexmap = "1.3"
itertools = "0.8.2"
md-5 = "0.8"
prettytable-rs = "0.8.0"
git2 = { version = "0.11.0", default-features = false }
regex = "1.3.1"
rusoto_autoscaling = "0.42.0"
rusoto_cloudformation = "0.42.0"
rusoto_cloudfront = "0.42.0"
rusoto_core = "0.42.0"
rusoto_ec2 = "0.42.0"
rusoto_elbv2 = "0.42.0"
rusoto_rds = "0.42.0"
rusoto_s3 = "0.42.0"
rusoto_sts = "0.42.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
uuid = { version = "0.8", features = ["v4"] }
