[package]
name = "awsx"
version = "0.1.0"
edition = "2018"

authors = [
    "Pit Kleyersburg <pit.kleyersburg@takkt.com>",
    "TAKKT Industrial & Packaging GmbH <webshop-devops@kaiserkraft-europa.de>",
]
license = "Apache-2.0"

autobins = false
publish = false

[[bin]]
name = "awsx"
path = "src/bin/main.rs"

[dependencies]
atty = "0.2.13"
backtrace-sys = "=0.1.19"
failure = "0.1.5"
futures = "0.1.28"
indexmap = "1.0"
itertools = "0.8.0"
md-5 = "0.8"
prettytable-rs = "0.8.0"
regex = "1.2.1"
rusoto_autoscaling = "0.40.0"
rusoto_cloudformation = "0.40.0"
rusoto_cloudfront = "0.40.0"
rusoto_core = "0.40.0"
rusoto_ec2 = "0.40.0"
rusoto_elbv2 = "0.40.0"
rusoto_rds = "0.40.0"
rusoto_s3 = "0.40.0"
rusoto_sts = "0.40.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.2"
uuid = { version = "0.7", features = ["v4"] }
