[package]
name = "awsx"
version = "0.1.0"
edition = "2018"

authors = [
    "Pit Kleyersburg <pit.kleyersburg@takkt.com>",
    "TAKKT Industrial & Packaging GmbH <webshop-devops@kaiserkraft-europa.de>",
]
license = "Apache-2.0"

[dependencies]
failure = "0.1.5"
futures = "0.1.25"
indexmap = "1.0"
md-5 = "0.8"
rusoto_cloudformation = "0.36.0"
rusoto_core = "0.36.0"
rusoto_sts = "0.36.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.2"
uuid = { version = "0.7", features = ["v4"] }
